### ISSUE TITLE
代码Word读入是否有问题

### ISSUE THREAD

**Issue by muye5** [Leonard-Xu/CWE#1]
test case的vocabulary只有一个

**Comment by leopard1** [comment]
希望您能否更加具体的描述问题

**Comment by Leonard-Xu** [comment]
希望您能更加具体的表述问题。

**Comment by muye5** [comment]
跑了下readme中的例子，输入：你好 世界
我理解在输出的word.txt中应该是每个word的向量表示啊，但是输出的只有一个标记句子开始的字 ，是不是我哪里理解的不对？命令是这个

```
./cwe -train corpus.txt -output-word word.txt -output-char char.txt
```

**Comment by Leonard-Xu** [comment]
是这样的，缺省的-min-count是5，也就是说所有出现次数小于5的词都会被忽略，你可以修改这个参数进行测试。建议您使用更大的语料进行训练。
