### ISSUE TITLE
wordsim datasets

### ISSUE THREAD

**Issue by bryandeng** [Leonard-Xu/CWE#2]
In your paper 

**3.2 Word Relatedness Computation**

> In this paper, we select two datasets, wordsim-240 and wordsim-296 for evaluation.

Could you tell me where to get such datasets?

**Comment by Leonard-Xu** [comment]
I have uploaded the dataset. These data are considered to be public and they are NOT created by the authors of the paper.

**Comment by bryandeng** [comment]
Thanks!
