### ISSUE TITLE
does this code support gpu and cpu ?

### ISSUE THREAD

**Issue by Priyansh2** [Leonard-Xu/CWE#8]
Is this code support gpu and cpu . If yes, then can you tell me which argument will take cpu cores and gpu (cuda backend).

**Comment by innerfirexy** [comment]
Priyansh2, the code is based on Google's word2vec project (Apache 2.0 License). So I don't think there is gpu support.

**Comment by innerfirexy** [comment]
> Is this code support gpu and cpu . If yes, then can you tell me which argument will take cpu cores and gpu (cuda backend).

Priyansh2, the code is based on Google's word2vec project (Apache 2.0 License). So I don't think there is gpu support.
